export { default as App } from "./App";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Products } from "./Products";
export { default as UpdateProduct } from "./UpdateProduct";
export { default as DeleteProduct } from "./DeleteProduct"
export { default as CreateProduct } from "./CreateProduct";
export { default as Home } from "./Home";
export { default as NavBar } from "./NavBar";
export { default as SingleProduct } from "./SingleProduct";
export { default as Cart } from "./Cart";